log: True
loggers:
  - class_name: lightning.pytorch.loggers.CometLogger
    params:
      save_dir: ${general.logs_folder_name}
      workspace: ${general.workspace}
      project_name: ${general.project_name}
      api_key: ${private.comet_api}
      experiment_name: ${general.run_name}
